// Turns the three bench.mjs JSON outputs into a side-by-side Markdown report.
//
// Usage:  node report.mjs results/memory.json results/stateful.json results/stateful-backpressure.json
// Writes RESULTS.md next to this script and prints it to stdout.

import { readFileSync, writeFileSync } from 'node:fs';

const files = process.argv.slice(2);
if (files.length === 0) {
  console.error('usage: node report.mjs <result.json> [<result.json> ...]');
  process.exit(1);
}
const runs = files.map((f) => JSON.parse(readFileSync(f, 'utf8')));

// Pull a single server metric value (optionally matching a tag substring) from
// the scraped Prometheus lines a run captured.
function metric(run, prefix, tagMatch) {
  const lines = (run.serverMetrics || []).filter(
    (l) => l.startsWith(prefix) && (!tagMatch || l.includes(tagMatch)));
  if (!lines.length) return null;
  const v = Number(lines[0].trim().split(/\s+/).pop());
  return Number.isFinite(v) ? v : null;
}

// Sum every matching series (e.g. all op tags of a *_total counter).
function metricSum(run, prefix, tagMatch) {
  const lines = (run.serverMetrics || []).filter(
    (l) => l.startsWith(prefix) && (!tagMatch || l.includes(tagMatch)));
  if (!lines.length) return null;
  return lines.reduce((acc, l) => acc + (Number(l.trim().split(/\s+/).pop()) || 0), 0);
}

const fmt = (v, d = 1) => (v == null ? '—' : Number(v).toFixed(d));
const row = (cells) => `| ${cells.join(' | ')} |`;

function table(title, header, rows) {
  return [
    `### ${title}`, '',
    row(header),
    row(header.map(() => '---')),
    ...rows.map(row),
    '',
  ].join('\n');
}

const modes = runs.map((r) => r.mode);
const header = ['Metric', ...modes];

const throughput = table('Throughput & latency (client-side)', header, [
  ['Iterations/sec', ...runs.map((r) => fmt(r.throughput.iterationsPerSec))],
  ['Completed ops/sec', ...runs.map((r) => fmt(r.throughput.completedOpsPerSec))],
  ['Confirms/sec', ...runs.map((r) => fmt(r.throughput.confirmsPerSec))],
  ['Hold p50 (ms)', ...runs.map((r) => fmt(r.latencyMs.hold.p50))],
  ['Hold p95 (ms)', ...runs.map((r) => fmt(r.latencyMs.hold.p95))],
  ['Hold p99 (ms)', ...runs.map((r) => fmt(r.latencyMs.hold.p99))],
  ['Confirm p50 (ms)', ...runs.map((r) => fmt(r.latencyMs.confirm.p50))],
  ['Confirm p95 (ms)', ...runs.map((r) => fmt(r.latencyMs.confirm.p95))],
]);

const outcomes = table('Outcomes', header, [
  ['Holds accepted', ...runs.map((r) => r.counts.held)],
  ['Holds rejected (sold out / lost race)', ...runs.map((r) => r.counts.holdRejected)],
  ['Confirmed', ...runs.map((r) => r.counts.confirmed)],
  ['Released', ...runs.map((r) => r.counts.released)],
  ['HTTP 5xx (write path)', ...runs.map((r) => r.counts.http5xx)],
  ['Read failures (GET detail 5xx)', ...runs.map((r) => r.counts.readErrors ?? 0)],
  ['Other client errors', ...runs.map((r) => r.counts.errors)],
]);

const server = table('Server-side (from /api/metrics)', header, [
  ['Confirms (server counter)', ...runs.map((r) => fmt(metricSum(r, 'cinetor_confirm_total', 'result="confirmed"'), 0))],
  ['Actor ask errors/timeouts', ...runs.map((r) => fmt(metricSum(r, 'cinetor_actor_ask_errors_total'), 0))],
  ['Backpressure max fill ratio', ...runs.map((r) => fmt(metric(r, 'cinetor_backpressure_max_fill_ratio'), 3))],
  ['Backpressure max mailbox size', ...runs.map((r) => fmt(metric(r, 'cinetor_backpressure_max_mailbox_size'), 0))],
  ['Backpressure active actors', ...runs.map((r) => fmt(metric(r, 'cinetor_backpressure_active_actors'), 0))],
]);

const cfg = runs[0].config;
const md = [
  '# Actor-mode comparison — results',
  '',
  '> Generated by `report.mjs` from `bench.mjs` runs. Numbers are from one machine',
  '> and one workload shape; treat them as a *shape*, not a benchmark of record.',
  '',
  '**Workload**: ' +
    `${cfg.vus} concurrent users, ${cfg.durationS}s, ${cfg.seats} seat(s)/hold, ` +
    (cfg.focusShow ? `single show \`${cfg.focusShow}\`` : `spread across ${cfg.shows} shows`) +
    `, \`${cfg.workload || 'journey'}\` pattern.`,
  '',
  throughput,
  outcomes,
  server,
  '## How to read this',
  '',
  '- **memory** is the original in-memory `ShowActor`: no disk, no flow control.',
  '- **stateful** journals every command + snapshots state, so seat bookings',
  '  survive a restart — the price is journaling latency on each hold/confirm.',
  '- **stateful-backpressure** adds a bounded, resizable mailbox. Under this',
  "  workload the batched journal keeps the actors from backing up, so the",
  '  mailbox stays shallow and backpressure never engages — it is a memory',
  '  safety-net for genuine overload, not a throughput knob.',
  '',
].join('\n');

const outPath = new URL('./RESULTS.md', import.meta.url).pathname;
writeFileSync(outPath, md);
process.stdout.write(md + '\n');
console.error(`\nwrote ${outPath}`);
